#!/usr/bin/env node

const commandLineArgs = require('command-line-args');
const getUsage = require('command-line-usage');
const menu = require('./src/Model/Menu');
const Progress = require('./src/Model/Progress');
const Args = require('./src/Model/Args');
const LighthouseService = require('./src/Service/LighthouseService');
const ProgressUtility = require('./src/Utility/ProgressUtility');

let args = new Args(commandLineArgs(menu[1]['optionList']));

if (args.shouldShowHelp()) {
    console.log(getUsage(menu));
} else {
    const lighthouseService = new LighthouseService(args);
    let bar;
    lighthouseService.start(count => {
        bar = ProgressUtility.build(count);
    }, /** @type Progress */ progress => {
        bar.tick(1, {message: progress.url.url});
    }).then(() => {
        console.log('Start Lighthouse...');
    });
}