#!/usr/bin/env node

const commandLineArgs = require('command-line-args');
const getUsage = require('command-line-usage');
const menu = require('./src/Model/Menu');
const Args = require('./src/Model/Args');
const LighthouseService = require('./src/Service/LighthouseService');
const ProgressUtility = require('./src/Utility/ProgressUtility');

let args = new Args(commandLineArgs(menu[1]['optionList']));

if (args.shouldShowHelp()) {
    console.log(getUsage(menu));
} else {
    args.output.doesFolderExist();
    const lighthouseService = new LighthouseService(args);
    let bar;
    lighthouseService.on('start', urls => {
        if (args.verbose) {
            bar = ProgressUtility.build(urls.length);
        }
    }).on('progress', url => {
        if (args.verbose) {
            bar.tick(1, {message: url.url});
        }
    }).on('complete', () => console.log('Done'));
    lighthouseService.start().then();
}